#cloud-config
autoinstall:
  source:
    search_drivers: false
  packages:
    - ubuntu-server-minimal
  apt:
    disable_components: []
    geoip: true
    preserve_sources_list: false
  drivers:
    install: false
  identity:
    hostname: test.vm
    password: $6$l9QXpP/Uy19Ve7vl$9Ysm.Wn/M9uldfBSp0EpTwzgpoQqdmJROLhNiK3TIDVwCqpJ0uofnXZCTqHd1IbRZM3beZPEJgDEMusQdA5C6.
    realname: lyynxxx
    username: lyynxxx
  kernel:
    package: linux-generic
  keyboard:
    layout: us
    toggle: null
    variant: ''
  locale: en_US.UTF-8
  network:
    network:
      ethernets:
        enwild:
          match:
            name: e*
          addresses: 
            - 192.168.0.118/24
          dhcp4: false
          gateway4: 192.168.0.1
          nameservers:
            addresses:
              - 192.168.0.1
      version: 2
  ssh:
    allow-pw: false
    authorized-keys: [ 'ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAsCaKUzXes0z4WMqY8tQ9PsTEFmYVIyj7nYd4F9iZXSHZfDv6AbyCudGVXHdrdAe4VnMmoWVg6j8k546KQzFZ3bQl5UJdWrqulwCvFrH8yEyouqmA6OeSSAz7ALG85FBYiVWVKWrlzLqAIT/Gn+Ud57Pu3d4OowH00EXqksKdeux/eT+nyGuC7Je2ecvXLqETOhOJDhAicZf8SEcu5Rsbz7dEqZPnXC+4zfibqDuldzKDEkYL4Pyc4mcG+F15yxmW0OyjMLUI93kcgtmwXVKRPV2k0ceuqa7a3zlhbwae/ofgC7AwsUBZYdxxSfxmkGIXZYfoaN1PxiXj+aiMFdis5w== tech-nopriv' ]
    install-server: true
  storage:
    config:
## Create a partition table on the disk
    - ptable: gpt
      path: /dev/sda
      wipe: superblock
      preserve: false
      name: ''
      grub_device: false
      type: disk
      id: disk-sda
## First partition for /boot/EFI
    - device: disk-sda
      size: 1127219200
      flag: boot
      number: 1
      preserve: false
      grub_device: true
      type: partition
      id: partition-0
## Filesystem for /boot/EFI
    - fstype: fat32
      volume: partition-0
      preserve: false
      type: format
      id: format-0
## Second partition for /boot
    - device: disk-sda
      size: 300M
      wipe: superblock
      flag: ''
      number: 2
      preserve: false
      grub_device: false
      type: partition
      id: partition-1
## Filesystem for /boot
    - fstype: xfs
      volume: partition-1
      preserve: false
      type: format
      id: format-1
## Third partition for LVM Volume Group
    - device: disk-sda
      size: -1
      wipe: superblock
      flag: ''
      number: 3
      preserve: false
      grub_device: false
      type: partition
      id: partition-2
## Add partition to Volume Group
    - name: vg00
      devices:
      - partition-2
      preserve: false
      type: lvm_volgroup
      id: lvm_volgroup-0
##########################################################################
## Define Logical Volume for tmp
    - name: lv-tmp
      volgroup: lvm_volgroup-0
      size: 1G
      wipe: superblock
      preserve: false
      type: lvm_partition
      id: lvm_tmp
## Define filesystem for tmp
    - fstype: xfs
      volume: lvm_tmp
      preserve: false
      type: format
      id: format-tmp
## Mount root
    - path: /tmp
      device: format-tmp
      type: mount
      id: mount-tmp
##########################################################################
## Define Logical Volume for var
    - name: lv-var
      volgroup: lvm_volgroup-0
      size: 3G
      wipe: superblock
      preserve: false
      type: lvm_partition
      id: lvm_var
## Define filesystem for var
    - fstype: xfs
      volume: lvm_var
      preserve: false
      type: format
      id: format-var
## Mount root
    - path: /var
      device: format-var
      type: mount
      id: mount-var
##########################################################################
## Define Logical Volume for usr
    - name: lv-usr
      volgroup: lvm_volgroup-0
      size: 4G
      wipe: superblock
      preserve: false
      type: lvm_partition
      id: lvm_usr
## Define filesystem for usr
    - fstype: xfs
      volume: lvm_usr
      preserve: false
      type: format
      id: format-usr
## Mount root
    - path: /usr
      device: format-usr
      type: mount
      id: mount-usr
##########################################################################
## Define Logical Volume for root
    - name: lv-root
      volgroup: lvm_volgroup-0
      size: 5G
      wipe: superblock
      preserve: false
      type: lvm_partition
      id: lvm_root
## Define filesystem for root
    - fstype: xfs
      volume: lvm_root
      preserve: false
      type: format
      id: format-root
## Mount root
    - path: /
      device: format-root
      type: mount
      id: mount-root
##########################################################################
## Define Logical Volume for opt
    - name: lv-opt
      volgroup: lvm_volgroup-0
      size: 1G
      wipe: superblock
      preserve: false
      type: lvm_partition
      id: lvm_opt
## Define filesystem for opt
    - fstype: xfs
      volume: lvm_opt
      preserve: false
      type: format
      id: format-opt
## Mount root
    - path: /opt
      device: format-opt
      type: mount
      id: mount-opt
##########################################################################
## Mount /boot
    - path: /boot
      device: format-1
      type: mount
      id: mount-1
## Mount /boot/EFI
    - path: /boot/efi
      device: format-0
      type: mount
      id: mount-0
  updates: security
  version: 1

  late-commands:
  - curtin in-target --target=/target -- lvextend -l 95%FREE /dev/vg00/lv-opt
  - curtin in-target --target=/target -- xfs_growfs /opt
  - curtin in-target --target=/target -- apt install -y mc git nftables
  - curtin in-target --target=/target -- apt-get -y --quiet=2 remove btrfs-progs ftp fuse3 ntfs-3g lxd-agent-loader mailcap mime-support snapd thermald tnftp wireless-regdb
  - curtin in-target --target=/target -- apt-get -y --quiet=2 autoremove
  - curtin in-target --target=/target -- apt-get clean
  - rm -rf /target/root/snap
  - rm -rf /target/snap
  - rm -rf /target/var/lib/snapd
  - rm -rf /target/var/snap
  - rm -rf /target/etc/systemd/system/snap*
